export const programTemplateCategories = [
  'Housing and Utilities',
  'Food and Nutrition',
  'Health Care',
  'Transportation',
  'Tax Credits',
  'Cash Assistance',
  'Child Care, Youth, and Education',
  'Food or Groceries',
  'Baby Supplies',
  'Managing housing costs',
  'Behavioral health',
  "Child's development",
  'Family planning',
  'Job resources',
  'Low-cost dental care',
  'Civil legal needs',
];
