name: 'Check Branch'

on:
  # Trigger the workflow on pull request,
  # but only for the main branch
  pull_request:
    branches:
      - main

jobs:
  check_branch:
    name: Check branch
    runs-on: ubuntu-latest
    
    steps:
      - name: Check branch
        if: github.base_ref == 'main' && github.head_ref != 'dev'
        run: |
          echo "ERROR: You can only merge changes into main from the dev branch."
          exit 1
