name: Check Branch

on:
  pull_request:

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        if: github.base_ref == 'dev' && github.head_ref != 'feat/dev-branch-workflow'
        run: |
          echo "ERROR: You can only merge the dev branch into main."
          exit 1