name: Check Branch

on: pull_request

jobs:
  check_branch:
    if: github.base_ref == 'main' && github.head_ref != 'dev'
    name: Check dev -> main
    runs-on: ubuntu-latest
    steps:
      - name: Throw error and exit
        run: |
          echo "ERROR: You can only merge the dev branch into main." && exit 1
