name: Check Branch

on:
  pull_request

jobs:
  check_branch:
    if: github.base_ref == 'dev' && github.head_ref != 'feat/dev-branch-workflow-asdf'
    name: Throw error for non dev branch into main
    runs-on: ubuntu-latest
    steps:
      - name: Throw error
        run: echo "ERROR You can only merge the dev branch into main."
      - name: Exit with unsuccessful termination
        run: exit 1
