name: Check Branch

on: pull_request

jobs:
  check_branch:
    name: Check dev -> main
    runs-on: ubuntu-latest
    steps:
      - name: dev into main
        if: github.base_ref == 'main' && github.head_ref == 'dev'
        run: echo "Your pull request is for dev into main." && exit 0
      - name: feature branch into dev
        if: github.base_ref == 'dev'
        run: echo "Your pull request is for a feature branch into dev." && exit 0
      - name: Throw error and exit
        if: github.base_ref == 'main' && github.head_ref != 'dev'
        run: |
          echo "ERROR: You can only merge the dev branch into main." && exit 1
